// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGa_YYjN6UkGBRKFfzf2GzYTDDRER1KPw',
    appId: '1:703849349617:web:640045c4899dae15e80450',
    messagingSenderId: '703849349617',
    projectId: 'chat-app-4d801',
    authDomain: 'chat-app-4d801.firebaseapp.com',
    storageBucket: 'chat-app-4d801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApo7v_rScxUBUQ7Aqn27Ldo-r1iBWHr34',
    appId: '1:703849349617:android:52ad74fbe8b9e6a5e80450',
    messagingSenderId: '703849349617',
    projectId: 'chat-app-4d801',
    storageBucket: 'chat-app-4d801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBABA9hGKlsCTJxzU4B7XTAk8lKGwNds4',
    appId: '1:703849349617:ios:3bc640b1380989f1e80450',
    messagingSenderId: '703849349617',
    projectId: 'chat-app-4d801',
    storageBucket: 'chat-app-4d801.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBABA9hGKlsCTJxzU4B7XTAk8lKGwNds4',
    appId: '1:703849349617:ios:b12311fddf97c65be80450',
    messagingSenderId: '703849349617',
    projectId: 'chat-app-4d801',
    storageBucket: 'chat-app-4d801.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
